[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/api/corporate/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
