CREATE OR REPLACE FUNCTION public.get_user_hotel_id() RETURNS TEXT LANGUAGE sql STABLE AS $$ SELECT COALESCE(auth.jwt() ->> 'hotel_id', current_setting('app.current_hotel_id', true)); $$;
CREATE OR REPLACE FUNCTION public.is_superadmin() RETURNS BOOLEAN LANGUAGE sql STABLE AS $$ SELECT (auth.jwt() -> 'user_metadata' ->> 'role') = 'superadmin'; $$;

ALTER TABLE IF EXISTS public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.partner_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hotel_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shuttle_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shuttle_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shuttle_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shuttle_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cruise_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.weekly_forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hotel_ops_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ops_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.superadmin_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.attenda_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff_checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff_checklist_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hotel_knowledge_base ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS hotels_select ON public.hotels;
DROP POLICY IF EXISTS hotels_insert ON public.hotels;
DROP POLICY IF EXISTS hotels_update ON public.hotels;
DROP POLICY IF EXISTS staff_accounts_select ON public.staff_accounts;
DROP POLICY IF EXISTS staff_accounts_insert ON public.staff_accounts;
DROP POLICY IF EXISTS staff_accounts_update ON public.staff_accounts;
DROP POLICY IF EXISTS requests_select ON public.requests;
DROP POLICY IF EXISTS requests_insert ON public.requests;
DROP POLICY IF EXISTS requests_update ON public.requests;
DROP POLICY IF EXISTS messages_select ON public.messages;
DROP POLICY IF EXISTS messages_insert ON public.messages;
DROP POLICY IF EXISTS messages_update ON public.messages;
DROP POLICY IF EXISTS partners_select ON public.partners;
DROP POLICY IF EXISTS partners_insert ON public.partners;
DROP POLICY IF EXISTS partners_update ON public.partners;
DROP POLICY IF EXISTS staff_checklists_select ON public.staff_checklists;
DROP POLICY IF EXISTS staff_checklist_instances_select ON public.staff_checklist_instances;
DROP POLICY IF EXISTS hotel_knowledge_base_select ON public.hotel_knowledge_base;
DROP POLICY IF EXISTS default_select ON public.partner_menu_items;
DROP POLICY IF EXISTS default_select ON public.qr_codes;
DROP POLICY IF EXISTS default_select ON public.hotel_rooms;
DROP POLICY IF EXISTS default_select ON public.shuttle_routes;
DROP POLICY IF EXISTS default_select ON public.shuttle_slots;
DROP POLICY IF EXISTS default_select ON public.shuttle_bookings;
DROP POLICY IF EXISTS default_select ON public.shuttle_requests;
DROP POLICY IF EXISTS default_select ON public.cruise_schedules;
DROP POLICY IF EXISTS default_select ON public.staff_schedules;
DROP POLICY IF EXISTS default_select ON public.weekly_forecasts;
DROP POLICY IF EXISTS default_select ON public.hotel_ops_tools;
DROP POLICY IF EXISTS default_select ON public.ops_tools;
DROP POLICY IF EXISTS default_select ON public.superadmin_config;
DROP POLICY IF EXISTS default_select ON public.attenda_fees;
DROP POLICY IF EXISTS default_select ON public.staff_checklists;
DROP POLICY IF EXISTS default_select ON public.staff_checklist_instances;
DROP POLICY IF EXISTS default_select ON public.hotel_knowledge_base;

CREATE POLICY hotels_select ON public.hotels FOR SELECT USING (true);
CREATE POLICY hotels_insert ON public.hotels FOR INSERT WITH CHECK (false);
CREATE POLICY hotels_update ON public.hotels FOR UPDATE USING (false);
CREATE POLICY staff_accounts_select ON public.staff_accounts FOR SELECT USING (false);
CREATE POLICY staff_accounts_insert ON public.staff_accounts FOR INSERT WITH CHECK (false);
CREATE POLICY staff_accounts_update ON public.staff_accounts FOR UPDATE USING (false);
CREATE POLICY requests_select ON public.requests FOR SELECT USING (auth.role() = 'authenticated' AND (public.is_superadmin() OR hotel_id::text = public.get_user_hotel_id()));
CREATE POLICY requests_insert ON public.requests FOR INSERT WITH CHECK (true);
CREATE POLICY requests_update ON public.requests FOR UPDATE USING (false);
CREATE POLICY messages_select ON public.messages FOR SELECT USING (auth.role() = 'authenticated' AND (public.is_superadmin() OR hotel_id::text = public.get_user_hotel_id()));
CREATE POLICY messages_insert ON public.messages FOR INSERT WITH CHECK (true);
CREATE POLICY messages_update ON public.messages FOR UPDATE USING (false);
CREATE POLICY partners_select ON public.partners FOR SELECT USING (auth.role() = 'authenticated' AND (public.is_superadmin() OR hotel_id::text = public.get_user_hotel_id()));
CREATE POLICY partners_insert ON public.partners FOR INSERT WITH CHECK (false);
CREATE POLICY partners_update ON public.partners FOR UPDATE USING (false);
CREATE POLICY default_select ON public.partner_menu_items FOR SELECT USING (true);
CREATE POLICY default_select ON public.qr_codes FOR SELECT USING (auth.role() = 'authenticated' AND (public.is_superadmin() OR true));
CREATE POLICY default_select ON public.hotel_rooms FOR SELECT USING (auth.role() = 'authenticated' AND (public.is_superadmin() OR true));
CREATE POLICY default_select ON public.shuttle_routes FOR SELECT USING (true);
CREATE POLICY default_select ON public.shuttle_slots FOR SELECT USING (true);
CREATE POLICY default_select ON public.shuttle_bookings FOR SELECT USING (false);
CREATE POLICY default_select ON public.shuttle_requests FOR SELECT USING (false);
CREATE POLICY default_select ON public.cruise_schedules FOR SELECT USING (true);
CREATE POLICY default_select ON public.staff_schedules FOR SELECT USING (true);
CREATE POLICY default_select ON public.weekly_forecasts FOR SELECT USING (true);
CREATE POLICY default_select ON public.hotel_ops_tools FOR SELECT USING (true);
CREATE POLICY default_select ON public.ops_tools FOR SELECT USING (true);
CREATE POLICY default_select ON public.superadmin_config FOR SELECT USING (false);
CREATE POLICY default_select ON public.attenda_fees FOR SELECT USING (false);
CREATE POLICY default_select ON public.staff_checklists FOR SELECT USING (true);
CREATE POLICY default_select ON public.staff_checklist_instances FOR SELECT USING (true);
CREATE POLICY default_select ON public.hotel_knowledge_base FOR SELECT USING (true);