export interface BlogPost {
  slug: string;
  num: string;
  category: string;
  categoryColor: string;
  title: string;
  subtitle: string;
  problem: string;
  /** SEO meta description — kept distinct from `problem` so it can be tuned to ~155 chars without touching on-page copy. */
  metaDescription: string;
  readingTime: string;
  content: string[];
  author: string;
  publishedDate: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "hotels-dont-have-an-information-problem",
    num: "01",
    category: "Operations",
    categoryColor: "#3B82F6",
    title: "Hotels Don't Have an Information Problem",
    subtitle: "They have an organization problem",
    problem: "Your team already creates everything you need to run the hotel. It's just scattered across apps, paper, radios, and people's heads.",
    metaDescription: "Independent hotels don't lack information — they lack a place to organize it. Here's why the fix isn't more software, it's one thread for every role.",
    readingTime: "5 min",
    publishedDate: "2026-05-12",
    author: "Alejandro Soria",
    content: [
      "Walk any independent hotel at 9am and you'll find the information already exists. Housekeeping knows which rooms are turned. The front desk knows who checked in late. The shuttle driver knows the airport is backed up. A supervisor knows the ice machine is down again. None of it is missing. It's just scattered.",
      "That's the real problem. Not a lack of information — a lack of organization. Schedules live in one app, checklists in a binder, SOPs in a manager's head, requests on a sticky note that disappears at shift change. Everyone is holding a piece, and no one can see the whole.",
      "So the manager spends the day chasing answers instead of making decisions. 'Did 214 get their towels?' 'Who closed the cash drawer?' 'Is the shuttle running?' Every answer requires a phone call, a radio, or a walk down the hall.",
      "Attenda's job is unglamorous and essential: put the information your team already creates somewhere everyone can actually use it. Requests, tasks, schedules, transportation, knowledge — one place, updated as the work happens. Not more data. Organized data.",
      "The test is simple. When the GM is off-property and wants to know how the day is going, can they see it in ten seconds — or do they have to call someone? If it's the phone call, you don't have an information problem. You have an organization problem.",
    ],
  },
  {
    slug: "cruise-day-shuttle-the-dollar7820-line-item",
    num: "02",
    category: "Revenue",
    categoryColor: "#158A7C",
    title: "Cruise-Day Shuttle: the $7,820 Line Item",
    subtitle: "How a 121-room boutique captured shuttle revenue in four months",
    problem: "How a 121-room boutique captured $7,820 in four months from cruise-day shuttle bookings — the math, the UI, the cruise calendar integration.",
    metaDescription: "A 121-room boutique hotel near PortMiami booked $7,820 in shuttle revenue in four months — no new staff, no new vehicle. Here's exactly how.",
    readingTime: "7 min",
    publishedDate: "2026-05-19",
    author: "Alejandro Soria",
    content: [
      "Port Everglades. PortMiami. Cape Canaveral. If your property is within 20 miles of a cruise port, you're leaving money on the table every week.",
      "Here's the math. A 121-room boutique hotel near PortMiami started tracking shuttle bookings through Attenda in February. By June — four months — they'd booked $7,820 in shuttle revenue. Not projected. Not estimated. Actual, trackable, attributable revenue.",
      "How? The shuttle booking form lives inside the guest QR code app. Guests tap 'Transport', pick a time, choose airport or cruise port, and confirm. The request hits the staff dashboard. The driver sees it on their phone. No phone calls. No 'I asked three hours ago'. No missed pickups.",
      "The cruise calendar integration is key. The hotel syncs cruise ship arrival dates — PortMiami publishes them months in advance. When a guest books during a cruise window, the shuttle is already factored into staffing. The hotel doesn't guess how many drivers they need. They know.",
      "Seven thousand, eight hundred and twenty dollars. From one feature, in one property, in four months. No new staff. No new vehicle. Just a QR code and a form that replaces the 'do you have a shuttle?' phone call that happens 40 times a day.",
    ],
  },
  {
    slug: "stop-answering-wheres-the-shuttle",
    num: "03",
    category: "Transportation",
    categoryColor: "#0EA5E9",
    title: "Stop Answering 'Where's the Shuttle?'",
    subtitle: "The one question that eats a front desk shift",
    problem: "A guest lands, calls the front desk, asks where the shuttle is. Multiply by every arrival. Live GPS answers it before the phone rings.",
    metaDescription: "Live GPS shuttle tracking answers 'where's the shuttle?' before the guest calls. How Attenda closes the loop between driver, front desk, and guest.",
    readingTime: "6 min",
    publishedDate: "2026-05-26",
    author: "Alejandro Soria",
    content: [
      "The guest exits the airport, looks around, checks their phone, and calls the hotel. The front desk agent — mid-check-in with another guest — puts them on hold to radio the driver. The driver is in traffic and can't answer. Another call comes in: same question. This happens all day, every arrival day.",
      "Nobody in that chain has the information they need. The guest doesn't know where the shuttle is. The front desk doesn't know where the shuttle is. Only the driver knows, and he's driving.",
      "Attenda closes the loop with live GPS. Through the Bouncie integration, the shuttle's real-time location, speed, and ETA are visible — to the guest on their phone, to staff on the dashboard, and to the manager watching the day. When the shuttle is half a mile out, everyone knows.",
      "The result isn't just fewer phone calls. It's coordination. Staff stage arrivals around real ETAs instead of guesses. Dispatch stops being a person shouting into a radio. And the guest waiting at the curb sees '4 minutes away' instead of wondering if they've been forgotten.",
      "Transportation is where independent hotels quietly lose guest confidence — and where a little visibility goes a long way. Stop answering 'where's the shuttle?' Give guests and staff the answer before the question.",
    ],
  },
  {
    slug: "ai-that-knows-when-not-to-guess",
    num: "04",
    category: "AI",
    categoryColor: "#F59E0B",
    title: "AI That Knows When Not to Guess",
    subtitle: "Assistance, not autonomy — and why that's the point",
    problem: "The dangerous AI in a hotel isn't the one that's wrong. It's the one that's confidently wrong. Attenda's assistant escalates instead of guessing.",
    metaDescription: "Most hotel AI fails by guessing confidently. Attenda's assistant answers only from approved knowledge and hands off the rest to a human.",
    readingTime: "6 min",
    publishedDate: "2026-06-01",
    author: "Alejandro Soria",
    content: [
      "Every AI-in-hospitality pitch promises the same thing: the software will run your hotel. Answer the guests, optimize the rates, manage the team. I've signed those contracts. The problem was never that the AI was wrong sometimes. It was that it was confidently wrong — and a hotel runs on trust.",
      "Attenda takes the opposite stance. The AI is an assistant to the operation, not the authority over it. It answers from what the hotel has actually approved — your SOPs, your procedures, your property knowledge. It can take a call, answer a common question, and route the rest to the right person.",
      "The most important thing it does is know its limits. When the answer isn't in the approved knowledge, it doesn't invent one. It hands off to a manager. 'AI that knows when not to guess' isn't a limitation — it's the whole point. Managers still decide. People still own the operation.",
      "That's also why the human input matters. Your team completes the checklists, logs the requests, records what happened. The AI organizes and surfaces that — it doesn't replace it. The magic isn't automation pretending to run a hotel. It's making the knowledge your people already have easy to reach.",
      "Ask any AI vendor one question: what happens when it doesn't know? If the answer is 'it answers anyway,' walk away. In a hotel, a confident wrong answer costs you a guest.",
    ],
  },
  {
    slug: "when-a-hotel-needs-a-manager-not-more-software",
    num: "05",
    category: "Management",
    categoryColor: "#6B7280",
    title: "When a Hotel Needs a Manager, Not More Software",
    subtitle: "The case for fractional hotel management",
    problem: "Sometimes the software isn't the problem — execution is. For qualified properties, a certified operator can run the operation on the platform.",
    metaDescription: "When more software won't fix an understaffed GM seat, a certified fractional hotel manager runs the operation on the platform instead.",
    readingTime: "6 min",
    publishedDate: "2026-06-03",
    author: "Alejandro Soria",
    content: [
      "There's a point some independent properties hit where more software won't help. The tools are fine. The problem is that no one on-site has the time — or the training — to run the operation the way it needs to be run. The owner is remote. The GM seat is empty or stretched thin. The team is doing its best without a captain.",
      "Software alone doesn't run a hotel. People do. That's not a knock on the technology — it's the reason the technology matters. A platform is only as good as the operator using it.",
      "So for qualified properties, Attenda can place a fractional hotel manager: a certified Attenda operator who runs the operation on the platform alongside your team. Not a consultant who writes a report and leaves. An operator who owns the daily execution — checklists, cash, transportation, guest recovery, staff accountability — using the same system your team sees.",
      "'Certified' matters here. These operators are trained across models — limited-service, extended-stay, full-service, boutique — because a select-service airport hotel and a boutique cruise-port property don't run the same way. The same operational problems appear in different clothes, and an operator who's seen them all closes the gap faster.",
      "This isn't for everyone, and it isn't meant to be. It's a premium engagement for properties that need execution, not just tools. If that's your situation, the question isn't which software to buy. It's who's going to run it.",
    ],
  },
  {
    slug: "from-3-8-to-4-7-stars-a-six-month-turnaround",
    num: "06",
    category: "Reviews",
    categoryColor: "#10B981",
    title: "From 3.8 to 4.7 Stars: a Six-Month Turnaround",
    subtitle: "The problem was never the rooms — it was the response time",
    problem: "The problem was never the rooms. It was the gap between 'I need towels' and 'towels arrived.' The fix, the timeline, the metric to watch.",
    metaDescription: "A 72-room hotel went from 3.8 to 4.7 stars in six months without touching the rooms. The fix was closing the gap between request and response.",
    readingTime: "5 min",
    publishedDate: "2026-06-05",
    author: "Alejandro Soria",
    content: [
      "A 72-room property in Florida was stuck at 3.8 stars on Google. The rooms were clean. The staff was friendly. The breakfast was solid. But the reviews kept saying the same thing: 'Asked for towels at 3pm. Never got them.' 'Called front desk three times about the A/C.' 'Waited 45 minutes for someone to bring a rollaway.'",
      "The problem wasn't the staff. It was the gap between request and response. Guests called the front desk. The front desk wrote it on a sticky note. The sticky note got lost during shift change. The next shift didn't know about it. The guest left a 2-star review.",
      "They deployed Attenda in February. Guests reached the hotel through its own welcome touchpoints — a link, a QR, at check-in — no app required. Staff dashboard on the front desk tablet. Every request logged, timestamped, assigned. When a guest asked for towels at 3pm, it appeared on the screen. Someone accepted it. Someone delivered it. The guest saw the status update on their phone.",
      "By August, six months later, they were at 4.7 stars. The rooms hadn't changed. The staff hadn't changed. The breakfast was the same. The only thing that changed was the gap between request and response — from 'who knows' to '7 minutes and 14 seconds' average.",
      "The metric to watch isn't your average rating. It's your average response time. Improve that, and the stars follow.",
    ],
  },
  {
    slug: "attenda-presence-never-a-silent-front-desk",
    num: "07",
    category: "Product",
    categoryColor: "#158A7C",
    title: "Attenda Presence: Never a Silent Front Desk",
    subtitle: "The two-sided realtime system for single-coverage hotels",
    problem: "One desk, one staff member, twelve reasons to step away — and no way for guests to know. The fix is Presence: a kiosk display, a phone console, and a log that never lies.",
    metaDescription: "Attenda Presence keeps single-coverage front desks from ever going silent — a kiosk display, a staff phone console, and a log that never lies.",
    readingTime: "6 min",
    publishedDate: "2026-08-08",
    author: "Alejandro Soria",
    content: [
      "Most independent hotels run single-coverage front desks. One person. One shift. One desk. That person checks guests in, answers the phone, calls housekeeping, restocks the lobby, walks the property, and takes their break. When they step away — for any reason — the desk is empty. The guest who walks up sees no one. They wait. They leave. They leave a review.",
      "The problem isn't that staff step away. They should. They have to. The problem is that the desk goes silent. No sign, no countdown, no way to ask for help. The guest stands there guessing whether someone is coming back in thirty seconds or thirty minutes.",
      "Attenda Presence fixes this with two devices and one realtime channel. A kiosk-locked tablet sits on the front desk. When staff is there, it shows an ambient screen — a clock, hotel info, rotating promos. When staff steps away, the display switches: an amber bar appears with a clear message, a reason, a live countdown, and a button to request assistance. The guest always knows the state of the desk.",
      "On the staff side, a phone app. One tap to step away — pick a reason (towels, guest assist, restock, property walk, break), pick a duration. The display updates in under a second. If a guest taps the assistance button while the desk is unattended, the staff member's phone vibrates immediately. They acknowledge it, head back, and the event is logged.",
      "The key design decision: guests never see 'overdue.' The countdown on the guest display floors at zero. If staff is late, the bar stays at 0:00. Overdue is a staff and admin concept — it shows in red on the phone console and in the admin dashboard, never on the guest-facing screen. Guests see calm. Staff see accountability.",
      "Every away session is logged server-side. Who stepped away, when, for how long, the reason, the estimated duration, the actual duration, and whether it ran overdue. Assist requests are timestamped — when the guest asked, when staff acknowledged, when it was resolved. This is labor-adjacent data, visible to GMs and owners, not to other staff.",
      "The display is offline-safe. If the network drops, it keeps functioning locally — it caches the last state, queues any assistance taps, and delivers them when the connection returns. No error states visible to guests. The service worker handles it. Staff see 'display offline' on their phone if the heartbeat is missed.",
      "We're building this for the properties that run lean. The ones where one person holds the desk and every minute away is a minute the guest notices. Presence doesn't add staff. It makes the staff you have visible — to guests, to themselves, and to the people managing the property.",
    ],
  },
  {
    slug: "hotel-guest-app-without-the-app-download",
    num: "08",
    category: "Guest Experience",
    categoryColor: "#EC4899",
    title: "The Hotel Guest App Nobody Has to Download",
    subtitle: "Why QR beats App Store for independent properties",
    problem: "Guests won't download an app for a two-night stay. A QR code that opens a page does everything an app promises, with zero install friction.",
    metaDescription: "Guests won't download a hotel app for a two-night stay. See why a QR code that opens straight to a web page outperforms native apps for independents.",
    readingTime: "5 min",
    publishedDate: "2026-08-11",
    author: "Alejandro Soria",
    content: [
      "A vendor once pitched me a hotel guest app with push notifications, loyalty points, and a mobile key. Great feature list. One problem: nobody was going to download it. A guest staying two nights is not installing an app, sitting through an onboarding flow, and creating an account to ask for extra towels. They're going to call the front desk, because calling is faster than downloading.",
      "That's the real competition for any hotel app: not other apps, but the phone call. And the phone call almost always wins, because it has zero friction. The fix isn't a better app. It's removing the download entirely.",
      "Attenda's guest side is a QR code. Scan it — on the welcome letter, at check-in, on a table tent by the elevator — and it opens straight to a page in the guest's existing browser. No App Store, no account, no password. They can request something, ask a question, or book the shuttle in the time it would've taken to find the front desk's phone number.",
      "This isn't a lesser version of an app. It's Progressive Web App architecture: same interactivity, same speed, same real-time updates as a native app, without the thing that kills adoption — the install step. Guests use it because using it costs nothing. Front desks see the request volume shift from phone calls to the dashboard, which means fewer interruptions and a written record of every ask.",
      "If you're evaluating hotel technology and 'app' is the pitch, ask one question: what percentage of your guests will actually install it? If the honest answer is under 20%, you're not buying a guest experience tool. You're buying an icon nobody taps.",
    ],
  },
  {
    slug: "reduce-front-desk-phone-calls-hotel",
    num: "09",
    category: "Operations",
    categoryColor: "#3B82F6",
    title: "The Front Desk Fields 200 Calls a Day. Most Shouldn't Be Calls.",
    subtitle: "Where the volume actually comes from, and how to route it",
    problem: "A busy front desk can field 150–200 calls a shift. Most are questions with a known answer — pool hours, wifi, checkout time — not that need a live person.",
    metaDescription: "A busy hotel front desk fields 150–200 calls a shift. Most are routine questions, not emergencies. Here's how to route them off the phone line.",
    readingTime: "6 min",
    publishedDate: "2026-08-13",
    author: "Alejandro Soria",
    content: [
      "Sit next to a front desk agent for one shift and count the calls. On a busy property it's 150 to 200. Now sort them: 'what time is checkout,' 'what's the wifi password,' 'is the pool open,' 'can I get a late checkout,' 'where do I park.' Maybe 15% are genuinely something only a person on-site can resolve. The other 85% are questions with a fixed, known answer — that still require a person to stop what they're doing, pick up, and answer it.",
      "That volume isn't a staffing problem you solve by hiring more front desk agents. It's a routing problem. The information exists — it's on a laminated card behind the desk, or in the GM's head — it's just not reachable without a phone call.",
      "Attenda's AI answering line and guest-facing knowledge base exist for exactly this stack of routine questions. The property loads its actual answers — pool hours, wifi credentials, parking instructions, checkout policy — once. From then on, a guest asking 'is the pool open' gets answered instantly, whether they ask the AI phone line, the QR page, or the front desk widget. No hold music. No interrupting a check-in to look up the wifi password for the fourth time that hour.",
      "The calls that do need a person still reach one — fast. Anything outside the approved knowledge escalates immediately rather than getting guessed at, which is the difference between an assistant and a liability (see 'AI That Knows When Not to Guess'). The point isn't fewer humans answering the phone. It's humans answering the calls that actually need a human.",
      "Count your own call log for a week and bucket it the same way. If 8 out of 10 calls are answerable from a card behind the desk, you don't have a staffing gap. You have an unrouted information problem, and it's costing your team the attention they need for the calls that matter.",
    ],
  },
  {
    slug: "hotel-partner-portal-fb-revenue-without-a-restaurant",
    num: "10",
    category: "Revenue",
    categoryColor: "#158A7C",
    title: "You Don't Need a Restaurant to Have F&B Revenue",
    subtitle: "How a vendor portal turns nearby businesses into a revenue line",
    problem: "Independent hotels without a restaurant lose F&B revenue by default. A vendor portal with curated local partners recovers it without a kitchen.",
    metaDescription: "No restaurant, no F&B revenue — unless you build a partner portal. How independent hotels turn nearby restaurants into a real revenue line.",
    readingTime: "6 min",
    publishedDate: "2026-08-15",
    author: "Alejandro Soria",
    content: [
      "Most independent, limited-service hotels don't have a restaurant, and the assumption that follows is that they don't have F&B revenue either. That assumption costs money every single night. Guests still want dinner. They're ordering it from somewhere — a delivery app that takes 25-30% and gives the hotel nothing, or a walk to a place they found on their own. Either way, the hotel is a bystander to a transaction happening on its own property.",
      "The fix isn't building a kitchen. It's building a relationship — formalized as a vendor portal. Attenda's partner system lets a hotel curate a handful of nearby restaurants, set a revenue share, and put ordering directly in the guest's QR page. The guest orders in-room. The partner fulfills it. The hotel takes a cut, automatically, on every order, with no staff involved beyond the initial partner agreement.",
      "The partner side matters as much as the guest side. Restaurants get a steady order channel with no marketing spend and a portal to manage their own menu, hours, and fulfillment — vendor-controlled, not hotel-controlled, so the relationship doesn't require staff babysitting every order. It's a real channel for them, not a favor.",
      "This same portal structure extends past food: local tours, spa services, transportation, anything a hotel would otherwise refer a guest to for free. Every one of those referrals is currently unmonetized goodwill. A vendor portal turns 'ask the front desk, they'll know a place' into a tracked transaction with a revenue share attached.",
      "If your property doesn't have a kitchen, you don't have a food cost problem to solve. You have an unbuilt partnership. The guest still eats dinner tonight — the only question is whether your hotel sees a cent of it.",
    ],
  },
  {
    slug: "daily-checklists-hotel-housekeeping-without-a-full-pms",
    num: "11",
    category: "Operations",
    categoryColor: "#3B82F6",
    title: "Your PMS Isn't a Checklist Tool. Stop Asking It to Be One.",
    subtitle: "Why housekeeping and daily ops need a separate system of record",
    problem: "PMS software is built for reservations and folios, not daily task execution. Forcing housekeeping checklists into it produces a system nobody uses.",
    metaDescription: "A PMS is built for reservations and folios, not daily checklists. Here's why forcing housekeeping tasks into it produces a system nobody actually uses.",
    readingTime: "5 min",
    publishedDate: "2026-08-17",
    author: "Alejandro Soria",
    content: [
      "Every PMS vendor eventually adds a 'housekeeping module.' It's usually a status flag — clean, dirty, inspected — bolted onto a room record. It answers one question well: is this room ready to sell. It answers almost nothing else. Did housekeeping check the smoke detector today? Restock the mini-fridge? Report the loose bathroom tile? That's not what a PMS was built to track, and it shows.",
      "The result on most properties is a shadow system: a paper checklist, a laminated sheet, a supervisor's memory of who did what. The PMS says the room is clean. Nobody can say whether the actual daily standards — the ones that separate a good hotel from a mediocre one — were met.",
      "That's a different problem than reservations and folios, and it deserves a different tool. Attenda's operations layer treats daily checklists, maintenance logs, and standards as their own system of record — assigned per shift, timestamped on completion, visible to a GM without walking the property. It doesn't replace the PMS. It handles what the PMS was never designed to handle.",
      "The visibility this creates is the actual value. A GM checking in remotely can see which rooms had their checklist completed today, not just which rooms are marked clean. A maintenance issue reported at 8am shows as open or resolved by 10am, not lost until someone happens to walk by again.",
      "If your 'housekeeping system' is a clean/dirty toggle in your PMS, you don't have a housekeeping system. You have a room-status flag wearing a housekeeping system's name. The daily standards that actually protect your reviews live somewhere else — usually paper, usually invisible to the person who owns the property.",
    ],
  },
  {
    slug: "independent-hotel-vs-franchise-software-flexibility",
    num: "12",
    category: "Management",
    categoryColor: "#6B7280",
    title: "Independent Hotels Don't Need Brand-Standard Software",
    subtitle: "Franchise ops tools are built for compliance. Yours should be built for you.",
    problem: "Franchise property-management tools exist to enforce brand standards across thousands of properties. An independent hotel with one location doesn't need that — it needs software built around how its own team actually works.",
    metaDescription: "Franchise operations software is built to enforce brand standards at scale. Independent hotels don't need compliance tooling — they need flexibility.",
    readingTime: "6 min",
    publishedDate: "2026-08-19",
    author: "Alejandro Soria",
    content: [
      "A branded hotel's operations software has one real job beneath the surface: make 4,000 properties behave identically. Every checklist, every workflow, every report exists so the brand can guarantee the same experience whether you're in Tampa or Tacoma. That's a legitimate and hard problem — for a franchise. It is not your problem if you own one independent property.",
      "Independent operators who adopt franchise-style tooling anyway usually do it because it's the software they've seen, not because it fits. The result is a system full of settings for scenarios that will never apply to a single 60-room boutique property, and none of the flexibility to configure the one workflow that's actually unique to how this specific hotel runs.",
      "An independent property's edge is that it can move. It can add a shuttle to a cruise port that a brand standard never anticipated. It can build a partner relationship with the restaurant next door. It can run a front desk with one person covering three roles, in a way a 200-page brand manual was never written to support.",
      "Attenda is built around that reality instead of against it: configurable per property, not standardized across a portfolio. The shuttle module, the partner revenue share, the checklist structure — all set up around how this hotel actually operates, not how a brand office in another state decided all hotels should operate.",
      "The question to ask before buying operations software isn't 'does this scale to thousands of properties.' It's 'does this fit the one property I actually run.' Those are different products, built for different jobs, and an independent hotel buying the first one is paying for compliance infrastructure it will never need.",
    ],
  },
  {
    slug: "remote-hotel-gm-dashboard-see-the-property-from-anywhere",
    num: "13",
    category: "Management",
    categoryColor: "#6B7280",
    title: "Running a Hotel You Can't Always Be At",
    subtitle: "What a remote GM actually needs to see, and how fast",
    problem: "Owners and regional managers overseeing multiple or distant properties need real visibility into today's operation, not a report that arrives next week.",
    metaDescription: "Owners overseeing a hotel from a distance don't need a weekly report — they need to see today's requests, staff activity, and revenue in real time.",
    readingTime: "6 min",
    publishedDate: "2026-08-20",
    author: "Alejandro Soria",
    content: [
      "A lot of independent hotels are run by owners who aren't standing behind the desk. Multi-property owners splitting attention. A GM covering two locations. An investor group that wants to know the operation is sound without flying in every week. All of them face the same gap: the reports that reach them are old by the time they arrive, and the property's actual daily reality — who's working, what guests are asking for, whether requests are getting closed — is invisible until something goes wrong enough to generate a phone call.",
      "That phone call is the failure mode. By the time an owner hears about a problem, it's usually already cost a review, a refund, or a guest who won't come back. Waiting for a monthly report to catch operational drift means catching it a month late.",
      "The fix is a dashboard that shows today, not last month. Attenda's GM and superadmin views surface live requests and their status, staff activity, shuttle bookings, revenue moments, and response times — the same information the on-site team sees, available from a phone anywhere. Not a summary generated overnight. The actual state of the property, right now.",
      "This matters most for the things that don't show up in a P&L until much later. A response-time average creeping up. A partner order that's been sitting unfulfilled for two hours. A front desk that's gone quiet during a shift nobody's watching. Those are visible today, in the dashboard, long before they're visible in a review score or a revenue dip.",
      "Owning a hotel you can't always be at doesn't have to mean flying blind between visits. It means picking a system that treats 'what's happening right now' as something you're entitled to see, not something you find out about when a guest complains loudly enough.",
    ],
  },
  {
    slug: "independent-hotel-tech-stack-what-actually-matters-2026",
    num: "14",
    category: "Technology",
    categoryColor: "#8B5CF6",
    title: "The Independent Hotel Tech Stack That Actually Matters",
    subtitle: "PMS, payments, ops layer — and what to skip",
    problem: "Independent hotels get pitched a dozen point solutions. Most only need three real layers: a PMS for the system of record, payments, and one operations layer connecting guests, staff, and vendors.",
    metaDescription: "Independent hotels don't need a dozen point solutions. Here's the three-layer tech stack that actually matters — and what to skip in 2026.",
    readingTime: "7 min",
    publishedDate: "2026-08-21",
    author: "Alejandro Soria",
    content: [
      "Every trade show floor for independent hotels is the same: forty booths, forty point solutions, each solving one sliver of the operation. A messaging tool. A housekeeping app. A review-management dashboard. A separate upsell platform. Bought individually, they add up to a stack that costs more than the problems they solve, with none of them talking to each other.",
      "Strip it back to what an independent property actually needs, and it's three layers. First: a PMS, as the system of record for reservations, rates, and folios — this is not optional and not worth replacing for most properties. Second: a payments layer that's actually integrated, not a separate terminal that requires re-keying totals. Third — and this is the layer most properties are missing — one operations layer connecting the guest, the staff, and any outside vendors, so requests, tasks, and transportation live somewhere everyone can see.",
      "Everything else on that trade show floor is usually a fragment of layer three, sold separately, at a markup, without the other fragments it needs to be useful. A standalone messaging tool without staff task visibility just moves the sticky note onto a screen. A standalone upsell platform without a delivery mechanism just adds another app nobody opens.",
      "The test for any new tool: does it replace a workflow, or does it add a fourth system that now needs to sync with the other three? If a vendor can't answer how their tool talks to your PMS and your existing ops layer, you're not simplifying your stack. You're adding to the pile that made the front desk's job harder in the first place.",
      "Three layers, chosen well and actually connected, beat twelve tools chosen individually every time. Before adding anything in 2026, ask which of the three it belongs to — and whether that layer is already covered.",
    ],
  },
  {
    slug: "hotel-staff-turnover-better-tools-not-more-pay",
    num: "15",
    category: "Staffing",
    categoryColor: "#F97316",
    title: "Staff Don't Quit the Hotel. They Quit the Chaos.",
    subtitle: "What turnover data says about tools, not just pay",
    problem: "Hotel staff turnover is usually blamed on wages, but a large share of exits trace back to daily friction — unclear tasks, no visibility, constant firefighting — that better operational tools directly reduce.",
    metaDescription: "Hotel staff turnover isn't only about wages. Unclear tasks and daily firefighting drive exits too — and better operational tools directly reduce both.",
    readingTime: "6 min",
    publishedDate: "2026-08-22",
    author: "Alejandro Soria",
    content: [
      "Ask any GM why staff leave and the first answer is pay. It's a real factor and it's not the whole answer. Talk to people who actually quit a front desk or housekeeping job and a different pattern shows up just as often: nobody could tell them clearly what needed to happen today, requests came in with no way to track them, and every shift felt like putting out fires nobody warned them about.",
      "That's not a compensation problem. It's a clarity problem, and it's fixable in a way a wage increase alone isn't. A front desk agent who knows exactly what's been asked of them, in what order, with a system that doesn't lose the request at shift change, is doing a fundamentally less stressful job than one working from memory and sticky notes — even at the identical hourly rate.",
      "Attenda's staff-side tools exist specifically to remove that chaos: clear task assignment, a request queue that doesn't disappear when a shift ends, a schedule and callout system that doesn't require a text-message chain to figure out who's covering today. None of it is glamorous. All of it is the daily texture of whether a job feels manageable or overwhelming.",
      "This shows up in the numbers that matter to an owner even before turnover does: response times, task completion rates, callout frequency. Properties running a clearer operational system tend to see fewer no-call-no-shows and fewer 'I just can't do this anymore' resignations, because the job itself got easier to do well.",
      "Raising pay is sometimes the right move and sometimes it's the easy move — treating a structural problem as if it were only a market-rate problem. Before assuming turnover is purely about the wage, ask your team what a normal shift actually feels like. If the answer involves the word 'chaos,' that's a tools problem, and it's cheaper to fix than a revolving door of new hires.",
    ],
  },
  {
    slug: "shuttle-scheduling-software-hotel-staffing-not-guesswork",
    num: "16",
    category: "Transportation",
    categoryColor: "#0EA5E9",
    title: "Stop Staffing Your Shuttle by Guesswork",
    subtitle: "Scheduling around real demand instead of a fixed loop",
    problem: "Most hotel shuttles run a fixed schedule regardless of actual demand, wasting driver hours on empty runs and leaving guests stranded during real peaks.",
    metaDescription: "Fixed shuttle loops waste driver hours on empty runs and strand guests during real peaks. Scheduling around actual bookings fixes both problems.",
    readingTime: "6 min",
    publishedDate: "2026-08-23",
    author: "Alejandro Soria",
    content: [
      "Most independent hotel shuttles run on a fixed loop: every 30 minutes, on the hour and the half, whether there's a guest waiting or not. It's simple to communicate and it's usually wrong. At 6am on a cruise-day Saturday, that 30-minute loop can't keep up — guests are stacking up at the curb with a boarding time to make. At 2pm on a Tuesday, the driver is making an empty round trip because the schedule said so, not because anyone needed it.",
      "That mismatch is a staffing cost hiding as a service standard. Every empty loop is paid driver time with no guest on board. Every overwhelmed peak is a guest who's now late, annoyed, or both — and telling other people about it in a review.",
      "The fix is scheduling around actual bookings instead of a fixed clock. When shuttle requests come through a real booking system — see the cruise-shuttle numbers in an earlier post — the hotel can see demand building hours or days ahead. A cruise-day Saturday with eleven bookings by 6am looks nothing like a quiet Tuesday, and staffing should reflect that difference instead of running the identical loop on both.",
      "This isn't about adding a second van. Most properties don't need more shuttle capacity — they need to deploy the capacity they have against where the demand actually is. A driver who knows there are three airport runs backed up between 7 and 8am can sequence them efficiently. A driver running a fixed loop with no visibility into demand can't do anything but follow the clock and hope.",
      "If your shuttle schedule was set once, years ago, and hasn't moved since, it's optimized for an average day that may not exist anymore. The properties getting real revenue and real guest satisfaction out of their shuttle are the ones scheduling against demand they can actually see — not a loop that was easy to print on a lobby sign.",
    ],
  },
  {
    slug: "hotel-qr-code-check-in-guest-experience",
    num: "17",
    category: "Guest Experience",
    categoryColor: "#EC4899",
    title: "The QR Code Is Doing More Work Than Your Check-In Desk",
    subtitle: "What actually happens after a guest scans",
    problem: "A hotel QR code is often just a wifi password. Used properly, it's the guest's entire channel to the property — requests, transport, dining, and questions, without a single app download.",
    metaDescription: "Most hotel QR codes just share a wifi password. Used properly, they're the guest's entire channel to the property — no app, no download, no friction.",
    readingTime: "5 min",
    publishedDate: "2026-08-24",
    author: "Alejandro Soria",
    content: [
      "Most hotel QR codes do one thing: connect to wifi. It's a fine use of a QR code and a wasted opportunity. The guest already has their phone out, already scanned something, already crossed the only friction barrier that matters — getting them to look at a screen connected to your property. Stopping at 'here's the password' leaves everything else on the table.",
      "A guest who scans a QR code at check-in is, for that moment, more receptive to what the hotel has to offer than at almost any other point in the stay. They're figuring out the property. They want to know what's around, what's included, how to get somewhere, who to ask for something. A wifi password answers none of that.",
      "Attenda's guest page is built to be the actual destination for that scan: property info, the ability to message the front desk directly, shuttle booking, local partner dining and experiences, and answers to the routine questions that would otherwise become a phone call. One page, no login, no download — everything the front desk would tell a guest if they walked up and asked, available the moment they scan.",
      "The measurable effect is a shift in where requests land. Instead of a phone call interrupting a check-in three doors down, the guest submits a request through the page they already have open, timestamped and visible to staff. The QR code stops being a wifi shortcut and starts being the front line of guest communication — quietly handling volume that used to hit the desk.",
      "If your property's QR code still only does wifi, you're using ten percent of what a guest is willing to do with their phone the moment they check in. The other ninety percent is requests, questions, and revenue you're currently routing through a phone call instead.",
    ],
  },
];

export const featuredBlogPosts = blogPosts.map(({ slug, num, category, categoryColor, title, problem, readingTime, author }) => ({
  slug, num, category, categoryColor, title, problem, readingTime, author,
}));
