import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://bdmmstatrsenidlgjock.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbW1zdGF0cnNlbmlkbGdqb2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MTE5MjAsImV4cCI6MjA5NDE4NzkyMH0.1pnioO5Y_3pW2LTaYc9aliRwTkGhX2cTNLrK9jI1P-4';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const hotelId = '7feb88fa-a72c-4c5d-b094-b4948bdab1d7';

const entries = [
  // ── SYSTEM GUIDE ──
  { category: 'System Guide', question: 'Getting Started with Attenda', answer: `Attenda is your daily operations engine. Here's how to get started:\n\n1. **Login**: Enter your staff PIN on the login screen. Your manager will provide this.\n2. **Dashboard**: The first screen shows today's activity, pending requests, and key metrics.\n3. **Navigation**: The sidebar has three sections:\n   - **Today**: Dashboard, Requests, Messages, Schedules\n   - **Operations**: Shuttle, KPIs, Knowledge Base, SOPs & Guide, Learning & HR, Property Info\n   - **Admin** (managers only): Shuttle Grid, Staff Callouts, Property Settings, Staff Management, Partners, QR Codes, Room Management\n4. **Hotel Switcher**: Superadmins can switch between properties using the dropdown at the top.\n5. **Sign Out**: Click Sign Out in the sidebar when done.`, keywords: ['getting started', 'login', 'navigation', 'basics', 'tutorial'] },

  { category: 'System Guide', question: 'Processing Guest Requests', answer: `Guest requests appear in the **Requests** tab with a badge count.\n\n**To process a request:**\n1. Open the Requests tab and see all guest requests grouped by type: All, Food, Transport, Amenities, Other\n2. Filter by Active / Completed / Messages tabs\n3. Click a request to expand it and see full details\n4. Click **In Progress** to start working on it, then **Mark Complete** when done\n5. Use the **Assign** field to assign a specific staff member\n\n**To create a manual request:**\n1. Click the **+ New Request** button\n2. Fill in guest name, room, type, and details\n3. Submit — it appears in the queue immediately\n\n**Transport sub-filter**: When viewing Transport requests, use airport/cruise/all to narrow down.`, keywords: ['requests', 'guest', 'orders', 'assign', 'complete', 'process'] },

  { category: 'System Guide', question: 'Using the Schedule & Forecast Tools', answer: `The **Schedules** tab shows a staff × day matrix for the selected week.\n\n**Navigation:**\n- Use ← Prev / Next → to move between weeks\n- Click **This week** to jump back to the current week\n\n**For Managers (Add Shifts):**\n1. Click **Add Shift**\n2. Enter staff name, date, role, start/end time, optional notes\n3. Click **Add Shift** — the staff member gets an email notification if their email is on file\n4. Click any shift block to remove it (confirmation required)\n\n**Forecast Row:**\nThe blue row at the top shows forecasted Occupancy %, Arrivals, and Rooms. Manager can click **Forecast** to input these numbers for the week.\n\n**Weekly Hours:**\nEach staff row shows their FT/PT status and actual hours vs minimum hours (e.g., "FT · 32h / 40h"). Green = meeting minimum, amber = below.\n\n**Staff: Request Off / Change:**\nStaff can click **Request Off** to submit a day-off/swap/cover request that managers see in the Staff Callouts tab.`, keywords: ['schedule', 'shift', 'forecast', 'hours', 'roster', 'staffing'] },

  { category: 'System Guide', question: 'Shuttle Operations Guide', answer: `The **Shuttle** tab manages all transportation operations.\n\n**Shuttle View (daily ops):**\n- See today's trips and bookings\n- Manage airport/cruise pickups and drop-offs\n- Track driver assignments\n\n**Shuttle Grid (admin):**\n- Calendar view of all shuttle slots\n- Create recurring or one-off slots\n- Assign routes to specific times\n\n**Route Management:**\nRoutes are configured in Property Settings. Standard routes include:\n- Airport pickup/drop-off (FLL)\n- Cruise port (Port Everglades)\n- Local area (restaurants, shopping)\n\n**Bookings:**\n- Guests request via the guest landing page (Transport tile)\n- Staff can also create bookings manually\n- Use Cancel to free up slots`, keywords: ['shuttle', 'transport', 'bus', 'driver', 'airport', 'cruise', 'pickup'] },

  { category: 'System Guide', question: 'Knowledge Base: Adding and Managing Content', answer: `The **Knowledge Base** tab powers the guest-facing chatbot and staff assistant.\n\n**Adding an entry:**\n1. Click **Add Entry**\n2. Choose a **Category** (General, WiFi, Amenities, Transport, Food, etc.)\n3. Write the **Question/Topic**\n4. Write the **Answer** with full details\n5. Add **Keywords** separated by commas (helps chatbot match)\n6. Click **Add to Knowledge Base**\n\n**Importing from URL:**\nPaste a URL and click **Import URL** to auto-extract the page title and body text as a draft entry.\n\n**Uploading PDF:**\nUpload a PDF document — Attenda extracts the text (up to 3000 chars) and creates a draft entry.\n\n**Editing / Deleting:**\nUse the pencil icon to edit, X icon to delete entries.\n\n**Activate / Deactivate:**\nToggle entries on/off. Deactivated entries don't appear in search results.\n\n**For SOPs**: Use the SOP / System Guide / Tenant Onboarding categories to create entries that appear in the SOPs & Guide tab.`, keywords: ['knowledge base', 'KB', 'faq', 'Q&A', 'import', 'PDF', 'chatbot'] },

  { category: 'System Guide', question: 'Staff Callouts & Change Requests', answer: `Staff can request time off, shift swaps, or schedule changes from the Schedules tab.\n\n**Staff flow:**\n1. Go to **Schedules** tab\n2. Click **Request Off** button\n3. Enter: your name, department, date, type of change (Day off / Swap / Cover / Time change / Other)\n4. Add reason/details (optional for Day off)\n5. Click **Send Request**\n\n**Manager flow:**\n1. See a **pending banner** at the top of the Schedules view showing recent requests\n2. Go to **Staff Callouts** tab in the Admin section for the full list\n3. Review each request — click **Resolve** to mark complete\n4. Resolved requests no longer appear in the list`, keywords: ['callouts', 'day off', 'PTO', 'time off', 'swap', 'cover', 'request'] },

  { category: 'System Guide', question: 'Learning & HR: Training and Policies', answer: `The **Learning & HR** tab stores training materials, policies, forms, and employee reference docs.\n\n**Two sections:**\n- **Learning**: Training materials, onboarding guides, SOP references\n- **HR Documents**: Company policies, benefits info, forms, employee handbook\n\n**How to add content:**\nManagers add entries through the **Knowledge Base** tab using:\n- Category: **Learning** (for training content)\n- Category: **HR** (for policy/HR content)\n\n**Search:**\nUse the search bar to find any document by title, content, or keywords.`, keywords: ['learning', 'HR', 'training', 'policies', 'handbook', 'forms'] },

  { category: 'System Guide', question: 'KPIs: Tracking Performance Metrics', answer: `The **KPIs** tab tracks key performance indicators for your property.\n\n**Available metrics:**\n- Revenue metrics (RevPAR, ADR, Occupancy)\n- Operations metrics (response times, request volume)\n- Guest satisfaction scores\n\n**How to use:**\n1. Select the **KPI Definition** tab to manage which KPIs to track\n2. Fill in **KPI Submissions** with daily/weekly values\n3. View historical data and trends\n\n**Auto-calculated:**\nSome KPIs pull from existing data (request volume, response times) automatically.`, keywords: ['KPI', 'metrics', 'performance', 'revenue', 'occupancy', 'tracking'] },

  { category: 'System Guide', question: 'QR Codes: Generating and Placing in Rooms', answer: `QR codes link each guest room to your property's Attenda landing page.\n\n**Generating a QR code:**\n1. Go to **QR Codes** tab\n2. Click **+ New QR Code**\n3. Enter a **label** (e.g., "Room 101")\n4. Select the **location type**: Room, Lobby, Common Area, Pool, Restaurant, etc.\n5. Click **Create**\n\n**URL format:**\nEach QR code links to: https://attendaapp.com/guest?hotel=YOUR_SLUG&room=ROOM_LABEL\n\n**Best practices:**\n- Use room-specific QR codes for personalized service\n- Use general QR codes in common areas for info only`, keywords: ['QR code', 'rooms', 'print', 'guest', 'scan', 'labels'] },

  // ── SOPs ──
  { category: 'SOP', question: 'Morning Shift Handoff Procedure', answer: `**Purpose**: Ensure smooth transition between overnight and morning shifts.\n\n**Steps:**\n1. **Arrive 10 min early** — clock in and review the passdown log\n2. **Read overnight notes** — check for any incidents, late check-ins, or guest issues\n3. **Run the daily brief** — open Attenda Dashboard to see: today's arrivals/departures, pending requests, occupancy, shuttle schedule\n4. **Check Knowledge Base** for any new SOP updates\n5. **Walk the property** — do a quick lobby, breakfast area, and parking lot check\n6. **Start the shift** — begin processing requests from the overnight queue\n\n**Passdown requirements:**\n- Note any unresolved guest issues\n- Flag VIP arrivals for the next shift\n- Document maintenance issues found during walk`, keywords: ['morning', 'handoff', 'shift', 'passdown', 'briefing'] },

  { category: 'SOP', question: 'Guest Check-In Procedure', answer: `**Purpose**: Provide a fast, friendly, and consistent check-in experience.\n\n**Steps:**\n1. **Greet** — "Welcome to [Hotel Name]! Checking in?"\n2. **Verify ID** — request valid government-issued photo ID\n3. **Confirm reservation** — pull up booking, confirm room type and dates\n4. **Collect payment** — process credit card for room + incidentals\n5. **Provide keys** — hand over room keys/cards and explain key policies\n6. **Direct to room** — give clear directions (floor, elevator location)\n7. **Offer amenities** — mention breakfast hours, wifi password, pool hours\n8. **Welcome** — "Enjoy your stay! Call the front desk if you need anything."\n\n**Special situations:**\n- **Early arrivals**: Offer baggage hold if room isn't ready\n- **VIP guests**: Notify manager on duty, offer upgrade if available\n- **Group bookings**: Pre-stage keys, designate check-in area`, keywords: ['check-in', 'arrival', 'guest', 'registration', 'front desk'] },

  { category: 'SOP', question: 'Guest Complaint Resolution SOP', answer: `**Purpose**: Resolve guest complaints professionally and consistently.\n\n**L.A.S.T. Method:**\n1. **Listen** — Let the guest explain without interrupting. Take notes on key details.\n2. **Apologize** — "I'm sorry this happened. I understand why this is frustrating."\n3. **Solve** — Offer a solution:\n   - Fix the problem immediately (maintenance, housekeeping)\n   - Offer compensation (discount, points, free breakfast)\n   - Upgrade room if available\n4. **Thank** — "Thank you for bringing this to our attention. We value your feedback."\n\n**Documentation:**\n1. Open Attenda → **Requests** tab\n2. Click **+ New Request**\n3. Set type to the relevant category\n4. Note the issue, resolution, and any compensation offered\n5. Mark as **Complete** once resolved\n\n**Escalation:**\n- If you cannot resolve within 5 minutes, notify the manager on duty\n- For safety/security complaints, escalate immediately`, keywords: ['complaint', 'issue', 'resolution', 'LAS', 'escalation', 'problem'] },

  { category: 'SOP', question: 'Housekeeping Inspection Checklist', answer: `**Purpose**: Maintain consistent room quality standards.\n\n**Daily inspection items:**\n□ Entry: Door closes properly, peephole clear, chain/lock functional\n□ Bathroom: Clean toilet, sink, shower/tub; fresh towels; stocked amenities (soap, shampoo, toilet paper, tissues)\n□ Bed: Fresh linens, no stains, pillows fluffed, bedspread straight\n□ Furniture: Dust-free, no scuffs, drawers close properly\n□ Floor: Vacuumed, no stains or debris\n□ TV/Remote: Working, batteries good, channel guide present\n□ AC/Heat: Thermostat working, set to appropriate temp (72°F default)\n□ Mini-fridge: Clean, empty if checkout, restocked if stayover\n□ Closet: Hangers present, ironing board available\n□ Window: Curtains straight, window locks secure\n□ Smoke detector: Present, not beeping\n\n**Mark room as:**\n✅ **Clean** — ready for next guest\n🟡 **Touch-up needed** — minor issues (mark in Attenda)\n🔴 **Out of order** — maintenance required before guest arrival`, keywords: ['housekeeping', 'inspection', 'room', 'clean', 'quality'] },

  // ── TENANT ONBOARDING ──
  { category: 'Tenant Onboarding', question: 'New Tenant Setup Checklist (Superadmin)', answer: `**Purpose**: Standard process for onboarding a new hotel onto Attenda.\n\n**Step 1 — Create the Hotel Record**\n1. Log in as **Super Admin** (PIN: 9999)\n2. Go to **Properties** tab\n3. Click **Add Property / Create Hotel**\n4. Fill in basic info: name, slug (URL-friendly), address\n5. Submit — this creates the hotel, API keys, and base configuration\n\n**Step 2 — Configure Property Settings**\n1. Switch to the new hotel using the hotel switcher dropdown\n2. Go to **Property Settings**\n3. Set: name, address, phone, email, logo\n4. Configure **Week Starts On** (Sunday or Monday)\n5. Set shuttle routes if applicable\n6. Set breakfast hours, wifi info, check-in/out times\n7. Save all settings\n\n**Step 3 — Add Staff**\n1. Go to **Staff Management**\n2. Add department heads first (GM, Front Desk Manager, Housekeeping Manager)\n3. Add all staff members with: name, email, department, role, PIN\n4. Set minimum weekly hours and employment type (FT/PT)\n5. Enter hire dates for PTO tracking\n\n**Step 4 — Configure QR Codes**\n1. Go to **QR Codes** tab\n2. Create QR codes for each room and common areas\n3. Print and place in rooms\n\n**Step 5 — Seed Knowledge Base**\n1. Go to **Knowledge Base** tab\n2. Add property-specific info (breakfast hours, pool hours, wifi, local attractions)\n3. Import from URL any existing property website content\n4. Activate key entries for the chatbot\n\n**Step 6 — Verify**\n1. Check guest landing page loads correctly\n2. Test staff PIN login\n3. Verify QR codes link to the correct hotel`, keywords: ['onboarding', 'new tenant', 'setup', 'configuration', 'superadmin', 'deploy'] },

  { category: 'Tenant Onboarding', question: 'Multi-Property Dashboard: Switching & Managing Hotels', answer: `**Purpose**: Managing multiple hotel properties from a single superadmin account.\n\n**Switching between properties:**\n1. Log in as **Super Admin** (PIN: 9999)\n2. Use the **hotel switcher dropdown** at the top of the sidebar\n3. Select the property you want to manage\n4. All tabs and data switch to that property\n\n**What carries over:**\n- Your superadmin credentials work across all properties\n- Each property has its own: staff accounts and PINs, guest requests and messages, shuttle routes and bookings, Knowledge Base entries, QR codes, room data, schedules, KPIs\n\n**What doesn't carry over:**\n- Each property is fully isolated — no data leaks between properties\n- Staff members cannot see other properties\n\n**Billing:**\n- Each property tracks its own payment type and last payment date\n- Superadmin can view all properties' billing status from the Properties tab\n\n**Best practices:**\n- Assign at least one manager per property\n- Set up each property's Knowledge Base independently\n- Train each site's manager on their Property Settings`, keywords: ['multi-property', 'switch', 'hotels', 'manage', 'superadmin', 'billing'] },
];

console.log(`Seeding ${entries.length} entries for hotel ${hotelId}...`);

let ok = 0, fail = 0;
for (const entry of entries) {
  const { error } = await supabase.from('hotel_knowledge_base').insert({
    hotel_id: hotelId,
    category: entry.category,
    question: entry.question,
    answer: entry.answer,
    keywords: entry.keywords || [],
    active: true,
  });
  if (error) {
    console.error(`❌ [${entry.category}] ${entry.question.slice(0, 60)}: ${error.message}`);
    fail++;
  } else {
    console.log(`✅ [${entry.category}] ${entry.question.slice(0, 60)}`);
    ok++;
  }
}

console.log(`\nDone! ${ok} seeded, ${fail} failed.`);
